### ISSUE TITLE
求解(手动解决)

### ISSUE THREAD

**Issue by Daangx** [c0olw/NacosRce#5]
师傅，在对自己的靶机测试时，发现自己打包的会注入失败，但是师傅提供的就可以成功，这是为什么呢？以下是截图，感谢师傅🙏
<img width="1051" alt="图片" src="https://github.com/c0olw/NacosRce/assets/126078418/55395f6d-b149-42ce-95b4-639decc3e1ed">

**Comment by c0olw** [comment]
应该是依赖冲突问题，换个方式打包可以解决问题。预计未来版本彻底解决掉这个问题。你可以试试我的打包方式，我在readme 那里贴出来了。

**Comment by Daangx** [comment]
感谢师傅解答

**Comment by Daangx** [comment]
师傅，通过对比，发现idea默认生成的MANIFEST.MF与师傅的存在差别，然后我用师傅的MANIFEST.MF进行替换后，就可以用了，打包方式就是readme里提到的Artifacts，更深层的原因我就不太清楚了，等待大手子解答
<img width="1298" alt="图片" src="https://github.com/c0olw/NacosRce/assets/126078418/6e5060b6-3dee-4ad3-af08-b4d2750bd995">
下面是师傅的
<img width="850" alt="图片" src="https://github.com/c0olw/NacosRce/assets/126078418/eaf94123-c490-47a9-8ad0-f50f2631aff9">
下面是我的idea自动生成的
<img width="881" alt="图片" src="https://github.com/c0olw/NacosRce/assets/126078418/c07c8707-c35f-4562-a95a-2964461ba213">

**Comment by rootphantomer** [comment]
> 师傅，在对自己的靶机测试时，发现自己打包的会注入失败，但是师傅提供的就可以成功，这是为什么呢？以下是截图，感谢师傅🙏 <img alt="图片" width="1051" src="https://user-images.githubusercontent.com/126078418/251341939-55395f6d-b149-42ce-95b4-639decc3e1ed.png">

注入失败的原因可以参考：https://github.com/c0olw/NacosRce/issues/3#issuecomment-1625101574   打包的问题，详见 pr
